In [6]:
import numpy as np
import pandas as pd
df = pd.read_csv('/content/Bitext_Sample_Customer_Support_Training_Dataset_27K_responses-v11.csv')
df.head(15)

,flags,instruction,category,intent,response
0,B,question about cancelling order {{Order Number}},ORDER,cancel_order,I've understood you have a question regarding ...
1,BQZ,i have a question about cancelling oorder {{Or...,ORDER,cancel_order,I've been informed that you have a question ab...
2,BLQZ,i need help cancelling puchase {{Order Number}},ORDER,cancel_order,I can sense that you're seeking assistance wit...
3,BL,I need to cancel purchase {{Order Number}},ORDER,cancel_order,I understood that you need assistance with can...
4,BCELN,"I cannot afford this order, cancel purchase {{...",ORDER,cancel_order,I'm sensitive to the fact that you're facing f...
5,BI,can you help me cancel order {{Order Number}}?,ORDER,cancel_order,"Of course, I'm here to assist you in canceling..."
6,BCLN,"I can no longer afford order {{Order Number}},...",ORDER,cancel_order,I pick up what you're putting down that you're...
7,BL,I am trying to cancel purchase {{Order Number}},ORDER,cancel_order,I've understood that you're seeking assistance...
8,BL,I have got to cancel purchase {{Order Number}},ORDER,cancel_order,I'm sensitive to the fact that you're seeking ...
9,BLQ,i need help canceling purchase {{Order Number}},ORDER,cancel_order,I perceive that you're seeking assistance with...
10,BQ,i dont know what to do to cancel order {{Order...,ORDER,cancel_order,I've taken note that you're unsure of the canc...
11,BL,I have a problem with cancelling purchase {{Or...,ORDER,cancel_order,I'm following you that you're facing difficult...
12,BL,problem with canceling purchase {{Order Number}},ORDER,cancel_order,I'm aware that you're facing difficulties canc...
13,BI,can you help me canceling order {{Order Number}}?,ORDER,cancel_order,I comprehend the urgency and complexity involv...
14,BLZ,help me canceling purchase {{Order Number}},ORDER,cancel_order,I catch on to the fact that you're seeking ass...

In [4]:
df.columns

Index(['flags', 'instruction', 'category', 'intent', 'response'], dtype='object')

In [8]:
df['instruction'].unique()

24635

In [9]:
df['category'].unique()

array(['ORDER', 'SHIPPING', 'CANCEL', 'INVOICE', 'PAYMENT', 'REFUND',
       'FEEDBACK', 'CONTACT', 'ACCOUNT', 'DELIVERY', 'SUBSCRIPTION'],
      dtype=object)

In [12]:
df['category'].value_counts()

category
ACCOUNT         5986
ORDER           3988
REFUND          2992
CONTACT         1999
INVOICE         1999
PAYMENT         1998
FEEDBACK        1997
DELIVERY        1994
SHIPPING        1970
SUBSCRIPTION     999
CANCEL           950
Name: count, dtype: int64

In [10]:
df['intent'].unique()

array(['cancel_order', 'change_order', 'change_shipping_address',
       'check_cancellation_fee', 'check_invoice', 'check_payment_methods',
       'check_refund_policy', 'complaint', 'contact_customer_service',
       'contact_human_agent', 'create_account', 'delete_account',
       'delivery_options', 'delivery_period', 'edit_account',
       'get_invoice', 'get_refund', 'newsletter_subscription',
       'payment_issue', 'place_order', 'recover_password',
       'registration_problems', 'review', 'set_up_shipping_address',
       'switch_account', 'track_order', 'track_refund'], dtype=object)

In [13]:
df['intent'].value_counts()

intent
contact_customer_service    1000
complaint                   1000
check_invoice               1000
switch_account              1000
edit_account                1000
contact_human_agent          999
check_payment_methods        999
delivery_period              999
newsletter_subscription      999
get_invoice                  999
payment_issue                999
registration_problems        999
cancel_order                 998
place_order                  998
track_refund                 998
change_order                 997
set_up_shipping_address      997
check_refund_policy          997
create_account               997
get_refund                   997
review                       997
delivery_options             995
delete_account               995
recover_password             995
track_order                  995
change_shipping_address      973
check_cancellation_fee       950
Name: count, dtype: int64

In [14]:
df['response'].value_counts()

response
Firstly, I truly understand how pivotal the {{Currency Symbol}}{{Refund Amount}} refund is for you. Every dollar counts, and we’re in this together. We acknowledge the importance of swift resolutions to your queries. Let me swiftly dive into the current status of your refund. As you patiently await, might I ask if you’ve ever had to follow up on a refund before? We value your insights and your patience alike. Rest assured, we're doing everything we can to ensure your satisfaction and trust.                                                                                                        2
Firstly, I truly understand how pivotal the {{Currency Symbol}}{{Refund Amount}} rebate is for you. Every dollar counts, and we’re in this together. We acknowledge the importance of swift resolutions to your queries. Let me swiftly dive into the current status of your rebate. As you patiently await, might I ask if you’ve ever had to follow up on a rebate before? We value your insights and your patience alike. Rest assured, we're doing everything we can to ensure your satisfaction and trust.                                                                                                        2
I'm sorry to hear that you're facing difficulties with online payments. I'm here to assist you in reporting this issue and finding a solution. To begin the process, please provide me with some more details about the problem you encountered during the payment. Did you receive any error messages or codes? Knowing these specifics will help us investigate and resolve the issue more efficiently. Thank you for bringing this to our attention, and rest assured that we are committed to resolving the problem and providing you with a seamless payment experience.                                          1
I apologize for the frustration you're facing with this payment issue. Rest assured, I'm here to provide you with the necessary assistance to resolve it. Please share the specific details of the payment issue you're encountering so that we can take appropriate actions to rectify it. Your feedback is valuable in helping us improve our payment system and ensure a smoother experience for all our customers. Thank you for reaching out, and together, we'll work towards a solution.                                                                                                                        1
I'm sorry to hear that you're experiencing problems with online payments. I'm here to provide you with the necessary assistance to inform us about these issues. Please provide me with more details about the specific problems you're encountering. This will help us gain a better understanding of the situation and find the most appropriate solution. Thank you for reaching out to us, and rest assured, we're committed to resolving this matter for you.                                                                                                                                                     1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ..
Always good to connect! I'm attuned to the fact that you need assistance to talk to someone. Rest assured, I'm here to help you with that. I will promptly connect you with one of our dedicated human representatives who will provide you with the support you need. Just give me a moment to make the arrangements. Stay with me, and we'll get you the assistance you're looking for.                                                                                                                                                                                                                              1
We value your outreach! I'm in tune with the fact that you are unsure of the steps to take in order to talk to a live agent. Allow me to guide you through the process and make it easier for you. To talk to a live agent, you can simply click on the "Chat" button on our website or app, or you can call our customer support hotline. Our agents are available to assist you and provide the help you need. If you need any further assistance or have any other questions, please feel free to let me know.                                                                                                      1
Your reach-out is appreciated! I'm sensing that you would like to speak with a human operator and I'm here to assist you. I apologize if you experienced any frustration, and I'll do my best to connect you with a live operator as quickly as possible. Your satisfaction is our priority, and we appreciate your patience. While I transfer your call, is there anything specific you would like to discuss or any particular issue you need assistance with? Your insights will help us provide you with the most suitable support. You're in good hands, and we'll work together to ensure your needs are met.    1
Always good to connect! I'm attuned to the fact that you need assistance to talk to a live agent. Rest assured, I'm here to help you with that. To connect you with a live agent, please provide me with some more details about your issue or query. This will help us ensure that the agent who assists you is well-equipped to address your specific needs. Your cooperation is greatly appreciated, and we'll get you connected to a live agent in no time.                                                                                                                                                        1
Thank you for reaching out! I completely understand that you want help to chat with a live agent. Your satisfaction is our top priority, and we are here to assist you every step of the way. Let me connect you with one of our highly skilled live agents who will be more than happy to address your concerns. Please bear with me for a moment while I assist you further.                                                                                                                                                                                                                                         1
Name: count, Length: 26870, dtype: int64

In [15]:
df['response'].nunique()

26870

In [16]:
response_counts = (
    df.groupby("instruction")["response"]
      .nunique()
      .sort_values(ascending=False)
)

response_counts.head(20)

instruction
can i order from {{Delivery City}}                          8
is it possible to place an order from {{Delivery City}}?    8
can I order from {{Delivery City}}?                         8
d uship to {{Delivery City}}                                8
can I place an order from {{Delivery City}}?                8
delieries to {{Delivery City}}                              8
is it possible to order from {{Delivery City}}?             8
is it possible to order from {{Delivery City}} ?            8
is it possible to order from {{Delivery City}}              8
deliveries to {{Delivery City}}                             8
can i place an order from {{Delivery City}}                 8
do you shp to {{Delivery City}}?                            8
do uship to {{Delivery City}}                               8
do you ship to {{Delivery City}}?                           8
do ya deliver to {{Delivery City}}                          8
is it possible to place an order from {{Delivery City}}     8
cn I place an order from {{Delivery City}}?                 8
shiping to {{Delivery City}}                                8
shipments to {{Delivery City}}                              8
do you deliver to {{Delivery City}} ?                       8
Name: response, dtype: int64

In [18]:
instruction_counts = df["instruction"].value_counts()
first_instruction = instruction_counts.index[0]
print(first_instruction)
df.loc[df["instruction"] == first_instruction,
       ["instruction", "category", "intent", "response"]]

shiping to {{Delivery City}}

,instruction,category,intent,response
11972,shiping to {{Delivery City}},DELIVERY,delivery_options,Unquestionably! I'm excited to assist you in e...
11993,shiping to {{Delivery City}},DELIVERY,delivery_options,Of course! I'm thrilled to inform you that we ...
12229,shiping to {{Delivery City}},DELIVERY,delivery_options,Unquestionably! We provide shipping services t...
12234,shiping to {{Delivery City}},DELIVERY,delivery_options,"Ah, the endless possibilities of shipping! Whe..."
12305,shiping to {{Delivery City}},DELIVERY,delivery_options,Sure! We are excited to offer our delivery ser...
12469,shiping to {{Delivery City}},DELIVERY,delivery_options,I'm happy to help! {{Delivery City}} is a deli...
12490,shiping to {{Delivery City}},DELIVERY,delivery_options,I'll get right on it! I'm excited to inform yo...
12602,shiping to {{Delivery City}},DELIVERY,delivery_options,Positively! Let's explore the available shippi...

In [21]:
df.isna().sum()

flags          0
instruction    0
category       0
intent         0
response       0
dtype: int64

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24635 entries, 0 to 24634
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   flags        24635 non-null  object
 1   instruction  24635 non-null  object
 2   category     24635 non-null  object
 3   intent       24635 non-null  object
 4   response     24635 non-null  object
dtypes: object(5)
memory usage: 962.4+ KB