In [3]:
import pandas as pd
import numpy as np

In [9]:
df=pd.read_csv('/content/Bitext_Sample_Customer_Support_Dataset_with_priority (1).csv')
df

,instruction,response,category,intent,priority
0,"['question', 'cancel', 'order', 'order', 'numb...","[""i've"", 'understand', 'question', 'regard', '...",ORDER,cancel_order,High
1,"['question', 'cancel', 'order', 'order', 'numb...","[""i've"", 'inform', 'question', 'cancel', 'orde...",ORDER,cancel_order,High
2,"['need', 'help', 'cancel', 'purchase', 'order'...","['sense', 'are', 'seek', 'assistance', 'cancel...",ORDER,cancel_order,High
3,"['need', 'cancel', 'purchase', 'order', 'number']","['understand', 'need', 'assistance', 'cancel',...",ORDER,cancel_order,High
4,"['afford', 'order', 'cancel', 'purchase', 'ord...","['am', 'sensitive', 'fact', 'are', 'face', 'fi...",ORDER,cancel_order,High
...,...,...,...,...,...
23885,"['get', 'use', 'account', 'category', 'profile...","['definitely', '!', 'appreciate', 'interest', ...",ACCOUNT,switch_account,Low
23886,"['wan', 'na', 'use', 'premium', 'profile', 'he...","['all', 'get', 'right', '!', 'sense', 'eagerne...",ACCOUNT,switch_account,Low
23887,"['need', 'use', 'account', 'category', 'account']","['appreciate', 'interest', 'leverage', 'benefi...",ACCOUNT,switch_account,Low
23888,"['change', 'platinum', 'account']","['fantastic', '!', 'am', 'excite', 'guide', 'p...",ACCOUNT,switch_account,Low
23889,"['try', 'change', 'account', 'type', 'account']","['appreciate', 'reach', 'us', 'regard', 'inten...",ACCOUN,NaN,NaN

In [10]:
df["category"].value_counts()

category
ACCOUNT         4996
ORDER           2993
CONTACT         1999
INVOICE         1999
PAYMENT         1998
FEEDBACK        1997
REFUND          1994
DELIVERY        1994
SHIPPING        1970
SUBSCRIPTION     999
CANCEL           950
ACCOUN             1
Name: count, dtype: int64

In [11]:
df["intent"].value_counts()

intent
check_invoice               1000
complaint                   1000
contact_customer_service    1000
edit_account                1000
check_payment_methods        999
get_invoice                  999
delivery_period              999
contact_human_agent          999
payment_issue                999
newsletter_subscription      999
registration_problems        999
cancel_order                 998
place_order                  998
set_up_shipping_address      997
review                       997
check_refund_policy          997
change_order                 997
get_refund                   997
create_account               997
delete_account               995
delivery_options             995
recover_password             995
change_shipping_address      973
check_cancellation_fee       950
switch_account                10
Name: count, dtype: int64

In [12]:
# Create a new priority column
df["priority"] = ""

##Priority Label Generation

####Business Rule for Priority Assignment

The original dataset contains customer support tickets with four attributes: instruction, response, category, and intent. However, it does not include a priority field, which is an important part of a customer support system.

To address this limitation, a new column named priority is generated using rule-based business logic. Instead of assigning priorities randomly, each ticket category is mapped to a priority level based on the urgency, business impact, and expected response time of the issue.

The priority levels are defined as follows:

High Priority: Tickets related to financial transactions or account access, such as Payment, Refund, and Account issues or a direct request to talk to customer support agent. These requests require immediate attention because they directly affect customer finances or access to services.


Medium Priority: Tickets related to operational processes, including Order, Shipping, Delivery, and Cancellation. These issues are important and time-sensitive but generally do not involve immediate financial or security risks.


Low Priority: General inquiries and informational requests, such as Invoice, Feedback, and Subscription. These requests typically do not require immediate action and have a comparatively lower business impact.

This rule-based labeling provides a consistent and explainable target variable for training the priority prediction model.

In [13]:
priority_map = {
    # High
    "complaint": "High",
    "payment_issue": "High",
    "contact_human_agent": "High",
    "contact_customer_service": "High",
    "check_refund_policy": "High",
    "cancel_order": "High",
    "check_cancellation_fee": "High",
    "registration_problems": "High",

    # Medium
    "place_order": "Medium",
    "change_order": "Medium",
    "track_order": "Medium",
    "delivery_period": "Medium",
    "delivery_options": "Medium",
    "create_account": "Medium",
    "recover_password": "Medium",
    "set_up_shipping_address": "Medium",
    "change_shipping_address": "Medium",
    "track_refund": "Medium",
    "get_refund": "Medium",

    # Low
    "delete_account": "Low",
    "switch_account": "Low",
    "edit_account": "Low",
    "check_invoice": "Low",
    "get_invoice": "Low",
    "check_payment_methods": "Low",
    "review": "Low",
    "newsletter_subscription": "Low"
}

df["priority"] = df["intent"].map(priority_map)

In [14]:
df["priority"] = df["intent"].map(priority_map)

In [15]:
df["priority"].value_counts()

priority
Medium    8948
High      7942
Low       6999
Name: count, dtype: int64

In [16]:
df[["intent", "priority"]].head(15)

          intent priority
0   cancel_order     High
1   cancel_order     High
2   cancel_order     High
3   cancel_order     High
4   cancel_order     High
5   cancel_order     High
6   cancel_order     High
7   cancel_order     High
8   cancel_order     High
9   cancel_order     High
10  cancel_order     High
11  cancel_order     High
12  cancel_order     High
13  cancel_order     High
14  cancel_order     High

In [17]:
df["priority"].isnull().sum()

np.int64(1)

In [18]:
df.to_csv(
    "Bitext_Sample_Customer_Support_Dataset_with_priority.csv",
    index=False
)

In [19]:
from google.colab import files

files.download("Bitext_Sample_Customer_Support_Dataset_with_priority.csv")